export default {
    LOGIN: 'LOGIN',
    CREATE: 'CREATE',
    FIND_TEMPLATE: 'FIND TEMPLATE',
    UPDATE_TEMPLATE: 'UPDATE TEMPLATE',
    FIND_COMPANY: 'FIND COMPANY',
    FIND_SOURCE_CONFIG: 'FIND SOURCE CONFIG',
    UPDATE_SOURCE_CONFIG: 'UPDATE SOURCE CONFIG',
}